services:
  dbneo4j:
    image: neo4j:4.4.8-enterprise
    container_name: dbneo4j
    volumes:
     # - ./Users/rayner/Downloads/docker_prueba_neo/neo4j/data/data:/
     # - ./Users/rayner/Downloads/docker_prueba_neo/neo4j/plugins:/
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import 
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms.unmanaged_extension_classes=n10s.endpoint=/rdf
      - NEO4_dbms.security_procedures_whitelist=apoc.*,n10s.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*,apoc.export.*,apoc.import.*,ns10.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*,n10s.*
      - NEO4J_dbms_memory_heap_initial__size=1024m
      - NEO4J_dbms_memory_heap_max__size=1.5G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__listen__address=35.215.253.124
      - NEO4J_dbms_default_advertised_address=repositoriotesisups.online
      - NEO4J_dbms_connector_bolt_listen_address=:7687
      - NEO4J_dbms_connector_bolt_advertised_address=:80
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4jArticulos2
      - NEO4JLABS_PLUGINS='["graph-data-science","apoc"]'
      - NEO4J_AUTH=neo4j/test      
  nginx_proxy_demo:
    image: nginx:latest
    container_name: nginx_proxy_demo
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dbneo4j
      - mongo
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    volumes:
      - ./mongoDB/data:/data/db
    expose:
      - "27017"

